#ensure to include homescreen and statscreen kv files for usage

#:include ./homescreen.kv
#:include ./statscreen.kv


#WindowManager:

#    HomeScreen:

#    Window2:

#temp layout of screens
GridLayout:
    cols: 1
    ScreenManager:
        id: screen_manager

        HomeScreen:
            name: "home_screen"
            id: home_screen

        StatScreen:
            name:"stat_screen"
            id: stat_screen
